name: buttmd_ext
description: 〝For to Buttress up with Generic MarkDown, like the Flying Buttresses〟.
version: 1.0.0
repository: https://github.com/LingaDocka/ButtMDExtension

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  markdown: ^7.2.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
